apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      containers:
      - env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: worker
        name: worker
        resources: {}
        volumeMounts:
        - mountPath: /usr/app/node_modules
          name: worker-claim0
        - mountPath: /usr/app
          name: worker-claim1
      restartPolicy: Always
      volumes:
      - name: worker-claim0
        persistentVolumeClaim:
          claimName: worker-claim0
      - name: worker-claim1
        persistentVolumeClaim:
          claimName: worker-claim1
status: {}
