version: '3'
services:

  postgres:
    image: 'postgres:latest'
#
  redis:
    image: 'redis:latest'
#
#
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4000:80'
#
#
  api:
    depends_on:
      - redis
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      # - PG_PASSWORD=example
      - PG_PORT=5432
      - EXPRESS_PORT=5000

#
  worker:
    depends_on:
      - api
      - redis
      - postgres
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#
  client:
    depends_on:
      - api
      - redis
      - postgres
      - worker
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
      # variableName=xxxxxxx # takes the variable from the code
      # variableName # takes it from your env
# REDIS_HOST || 'http://localhost';
# REDIS_PORT || 6789;
# PG_USER;
# PG_HOST || 'http://localhost';
# PG_DATABASE;
# PG_PASSWORD;
# PG_PORT || 3003;
