apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
      - name: fibonacci-worker
        image: fabianmoronzirfas/fibonacci-worker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        # ports:
        # - containerPort: <Port>
