apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server-deploymnet
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: fibonacci-server
        image: fabianmoronzirfas/fibonacci-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        # env:
        #   - REDIS_HOST=redis
        #   - REDIS_PORT=6379
        #   - PG_USER=postgres
        #   - PG_HOST=postgres
        #   - PG_DATABASE=postgres
        #   - PG_PASSWORD=postgres_password
        #   # - PG_PASSWORD=example
        #   - PG_PORT=5432
        #   - EXPRESS_PORT=5000
