apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-postgres-deployment
spec:
# don't just increase the replicas amount without
# making postgres aware of it
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - name: fibonacci-postgres
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
